// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
        ASSETS: Fetcher;
        OPENAI_API_KEY?: string;
        CLOUDFLARE_API_TOKEN?: string;
        CLOUDFLARE_ACCOUNT_ID?: string;
        GEMINI_API_KEY?: string;
        GOOGLE_API_TOKEN?: string;
}
