// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {

  ASSETS: Fetcher;
  DB: D1Database;
  CACHE: KVNamespace;
  BUCKET: R2Bucket;
  VECTORIZE: VectorizeIndex;
  SESSION_DO: DurableObjectNamespace;
  OPENAI_API_KEY: string;
  GEMINI_API_KEY: string;
  GITHUB_TOKEN: string;

}
